<?php

declare(strict_types=1);

return [
    'title' => 'Ход SaaS-перехода',
    'subtitle' => 'Безопасная перестройка Market Platform под SaaS, демо-контур и привлечение новых клиентов.',
    'last_updated_at' => '2026-06-25',
    'access' => [
        'allowed_user_ids' => [1],
        'allowed_user_emails' => ['321_123@bk.ru'],
    ],
    'current_focus' => 'Продолжить перевод Filament resources/pages на единый MarketContext без включения tenant scope.',
    'next_step' => 'Выбрать следующий малорисковый resource/page и заменить локальное определение market_id на MarketContext.',
    'release_policy' => 'Страница Ход работ выведена на prod. Следующие SaaS-изменения: local/staging сначала, prod только с flags off и отдельным подтверждением.',
    'stages' => [
        [
            'key' => 'safety_contour',
            'title' => '0. Защитный контур',
            'weight' => 8,
            'status' => 'done',
            'summary' => 'Правила, документы и ограничения, чтобы параллельные задачи не повредили prod.',
            'items' => [
                ['title' => 'Prod safety правила добавлены в AGENTS.md', 'status' => 'done'],
                ['title' => 'Создан подробный prod-safety runbook', 'status' => 'done'],
                ['title' => 'Создан технический SaaS-план', 'status' => 'done'],
                ['title' => 'Создан план привлечения клиентов', 'status' => 'done'],
                ['title' => 'Создан мастер-план с аварийным восстановлением', 'status' => 'done'],
                ['title' => 'Отдельная ветка/worktree для SaaS-работ', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'progress_page',
            'title' => '0.1. Страница Ход работ',
            'weight' => 4,
            'status' => 'done',
            'summary' => 'Видимый чек-лист прогресса в админке, без миграций и без записи в prod-данные.',
            'items' => [
                ['title' => 'Источник чек-листа в коде', 'status' => 'done'],
                ['title' => 'Read-only Filament page', 'status' => 'done'],
                ['title' => 'Доступ только владельцу проекта', 'status' => 'done'],
                ['title' => 'Автотест персонального доступа', 'status' => 'done'],
                ['title' => 'Локальная проверка синтаксиса и кодировок', 'status' => 'done'],
                ['title' => 'Staging/prod rollout после подтверждения', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'market_context',
            'title' => '1. MarketContext',
            'weight' => 14,
            'status' => 'done',
            'summary' => 'Единый источник текущего market_id без включения global scope.',
            'items' => [
                ['title' => 'Safe flags в .env.example', 'status' => 'done'],
                ['title' => 'config для market context', 'status' => 'done'],
                ['title' => 'Сервис MarketContext', 'status' => 'done'],
                ['title' => 'Поддержка super-admin выбранного рынка', 'status' => 'done'],
                ['title' => 'Поддержка withMarket для jobs/API', 'status' => 'done'],
                ['title' => 'Тесты MarketContext', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'market_scope',
            'title' => '2. MarketScope',
            'weight' => 14,
            'status' => 'done',
            'summary' => 'Framework-level scope за feature flag, чтобы изоляция не зависела от ручных фильтров.',
            'items' => [
                ['title' => 'BelongsToMarket trait', 'status' => 'done'],
                ['title' => 'MarketScope', 'status' => 'done'],
                ['title' => 'Режим disabled/shadow при flags off', 'status' => 'done'],
                ['title' => 'Тесты scope enabled/disabled', 'status' => 'done'],
                ['title' => 'Явный bypass для системных сценариев', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'resources_and_context',
            'title' => '3. Ресурсы, dashboard, API, jobs',
            'weight' => 16,
            'status' => 'in_progress',
            'summary' => 'Перевод ключевых экранов и фоновых сценариев на единый market context.',
            'items' => [
                ['title' => 'Support helpers используют единый context: TestingModeNoticeSettings + MarketFeature + TaskCalendarFilters переведены', 'status' => 'done'],
                ['title' => 'Filament resources используют единый context: ReportResource + ReportRunResource + MarketLocationTypeResource + MarketSpaceTypeResource + TaskCommentResource + TaskWatcherResource + MarketHolidayResource + MarketplaceSlideResource + StaffResource + StaffForm + IntegrationExchangeResource + StaffInvitationResource + StaffInvitationForm + MarketLocationResource + MarketSpaceGroupEpisodeResource + CreateMarketLocation + EditMarketLocation переведены', 'status' => 'in_progress'],
                ['title' => 'Dashboard/widgets используют единый context: 17 widget + Dashboard page переведены', 'status' => 'in_progress'],
                ['title' => 'Карта рынка использует тот же market_id', 'status' => 'pending'],
                ['title' => '1C API выставляет context из integration token', 'status' => 'pending'],
                ['title' => 'Jobs/commands получают market_id явно', 'status' => 'pending'],
                ['title' => 'Smoke matrix для UI/API/jobs', 'status' => 'pending'],
            ],
        ],
        [
            'key' => 'write_guards',
            'title' => '4. Write guards',
            'weight' => 14,
            'status' => 'pending',
            'summary' => 'Защита от cross-market связей при создании и обновлении данных.',
            'items' => [
                ['title' => 'Same-market validator/service', 'status' => 'pending'],
                ['title' => 'Guards для договоров и мест', 'status' => 'pending'],
                ['title' => 'Guards для начислений и платежей', 'status' => 'pending'],
                ['title' => 'Guards для документов и шаринга', 'status' => 'pending'],
                ['title' => 'Guards для marketplace', 'status' => 'pending'],
                ['title' => 'Cross-market tests create/update', 'status' => 'pending'],
            ],
        ],
        [
            'key' => 'demo_pilot',
            'title' => '5. Demo market и пилот',
            'weight' => 12,
            'status' => 'pending',
            'summary' => 'Безопасное демо с синтетическими данными и пилотный контур для первых клиентов.',
            'items' => [
                ['title' => 'demo:provision', 'status' => 'pending'],
                ['title' => 'demo:reset', 'status' => 'pending'],
                ['title' => 'Синтетические арендаторы, места, договоры и финансы', 'status' => 'pending'],
                ['title' => 'Демо-пользователи директор/админ/арендатор', 'status' => 'pending'],
                ['title' => 'Внешние интеграции в демо выключены', 'status' => 'pending'],
                ['title' => 'Demo script на 15 минут', 'status' => 'pending'],
            ],
        ],
        [
            'key' => 'landing_sales',
            'title' => '6. Сайт и воронка продаж',
            'weight' => 8,
            'status' => 'pending',
            'summary' => 'Сайт-визитка, заявка на демо, пилот и коммерческая воронка.',
            'items' => [
                ['title' => 'Landing page', 'status' => 'pending'],
                ['title' => 'Форма заявки', 'status' => 'pending'],
                ['title' => 'Сохранение и уведомления по заявкам', 'status' => 'pending'],
                ['title' => 'Презентация и КП', 'status' => 'pending'],
                ['title' => 'Таблица первых лидов', 'status' => 'pending'],
            ],
        ],
        [
            'key' => 'rollout',
            'title' => '7. Staging и prod rollout',
            'weight' => 10,
            'status' => 'pending',
            'summary' => 'Контролируемый выпуск: staging, flags off, smoke, потом prod только с подтверждением.',
            'items' => [
                ['title' => 'Staging deploy с flags off', 'status' => 'pending'],
                ['title' => 'Staging smoke с flags off', 'status' => 'pending'],
                ['title' => 'Staging smoke с flags on', 'status' => 'pending'],
                ['title' => 'Prod deploy с flags off', 'status' => 'pending'],
                ['title' => 'Prod flags on отдельным решением', 'status' => 'pending'],
                ['title' => 'Rollback drill через flags', 'status' => 'pending'],
            ],
        ],
    ],
    'risks' => [
        [
            'title' => 'Главный риск',
            'description' => 'Случайно повредить prod или скрыть данные из-за слишком раннего scope.',
            'mitigation' => 'Все scope/strict-write изменения только через flags, сначала local/staging, prod с flags off.',
        ],
        [
            'title' => '1C и фоновые процессы',
            'description' => 'API/jobs могут выполняться без session context.',
            'mitigation' => 'Перед включением scope все API/jobs должны явно выставлять MarketContext.',
        ],
        [
            'title' => 'Cross-market связи',
            'description' => 'FK проверяют существование записей, но не совпадение market_id.',
            'mitigation' => 'Write guards и тесты create/update для критичных сущностей.',
        ],
    ],
];
