<?php

declare(strict_types=1);

return [
    'title' => 'Ход SaaS-перехода',
    'subtitle' => 'Безопасная перестройка Market Platform под SaaS, демо-контур и привлечение новых клиентов.',
    'last_updated_at' => '2026-06-30',
    'access' => [
        'allowed_user_ids' => [1],
        'allowed_user_emails' => ['321_123@bk.ru'],
    ],
    'current_focus' => 'Демо-доступы безопасно выданы на staging через временный env-пароль, prod получил код с flags off и без записи demo-данных. Следующий маленький пакет — форма заявки на демо/пилот на landing page с отдельным хранением лидов и database-уведомлением владельцу.',
    'next_step' => 'Подготовить и проверить форму заявки на /demo: отдельная таблица demo_requests, POST с CSRF/throttle/honeypot, in-app уведомление владельцу 321_123@bk.ru и локальные regression-тесты. Деплой этого пакета требует PostgreSQL backup, потому что есть миграция.',
    'release_policy' => 'Работа идёт малыми пакетами: local/staging сначала, prod после успешного smoke без ожидания отдельного подтверждения, кроме миграций, .env, DB writes, flags или иных реальных рисков.',
    'stages' => [
        [
            'key' => 'safety_contour',
            'title' => '0. Защитный контур',
            'weight' => 8,
            'status' => 'done',
            'summary' => 'Правила, документы и ограничения, чтобы параллельные задачи не повредили prod.',
            'items' => [
                ['title' => 'Prod safety правила добавлены в AGENTS.md', 'status' => 'done'],
                ['title' => 'Создан подробный prod-safety runbook', 'status' => 'done'],
                ['title' => 'Создан технический SaaS-план', 'status' => 'done'],
                ['title' => 'Создан план привлечения клиентов', 'status' => 'done'],
                ['title' => 'Создан мастер-план с аварийным восстановлением', 'status' => 'done'],
                ['title' => 'Отдельная ветка/worktree для SaaS-работ', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'progress_page',
            'title' => '0.1. Страница Ход работ',
            'weight' => 4,
            'status' => 'done',
            'summary' => 'Видимый чек-лист прогресса в админке, без миграций и без записи в prod-данные.',
            'items' => [
                ['title' => 'Источник чек-листа в коде', 'status' => 'done'],
                ['title' => 'Read-only Filament page', 'status' => 'done'],
                ['title' => 'Доступ только владельцу проекта', 'status' => 'done'],
                ['title' => 'Автотест персонального доступа', 'status' => 'done'],
                ['title' => 'Локальная проверка синтаксиса и кодировок', 'status' => 'done'],
                ['title' => 'Staging/prod rollout после подтверждения', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'market_context',
            'title' => '1. MarketContext',
            'weight' => 14,
            'status' => 'done',
            'summary' => 'Единый источник текущего market_id без включения global scope.',
            'items' => [
                ['title' => 'Safe flags в .env.example', 'status' => 'done'],
                ['title' => 'config для market context', 'status' => 'done'],
                ['title' => 'Сервис MarketContext', 'status' => 'done'],
                ['title' => 'Поддержка super-admin выбранного рынка', 'status' => 'done'],
                ['title' => 'Поддержка withMarket для jobs/API', 'status' => 'done'],
                ['title' => 'Тесты MarketContext', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'market_scope',
            'title' => '2. MarketScope',
            'weight' => 14,
            'status' => 'done',
            'summary' => 'Framework-level scope за feature flag, чтобы изоляция не зависела от ручных фильтров.',
            'items' => [
                ['title' => 'BelongsToMarket trait', 'status' => 'done'],
                ['title' => 'MarketScope', 'status' => 'done'],
                ['title' => 'Режим disabled/shadow при flags off', 'status' => 'done'],
                ['title' => 'Тесты scope enabled/disabled', 'status' => 'done'],
                ['title' => 'Явный bypass для системных сценариев', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'resources_and_context',
            'title' => '3. Ресурсы, dashboard, API, jobs',
            'weight' => 16,
            'status' => 'in_progress',
            'summary' => 'Перевод ключевых экранов и фоновых сценариев на единый market context.',
            'items' => [
                ['title' => 'Support helpers используют единый context: TestingModeNoticeSettings + MarketFeature + TaskCalendarFilters переведены', 'status' => 'done'],
                ['title' => 'Filament resources/pages используют единый context: ReportResource + ReportRunResource + MarketLocationTypeResource + MarketSpaceTypeResource + TaskResource + TaskCommentResource + TaskWatcherResource + MarketHolidayResource + MarketplaceSlideResource + StaffResource + StaffForm + IntegrationExchangeResource + TenantResource + MarketSettings + MarketplaceSettings + MapReviewResults + OpsDiagnostics + OperationResource + StaffInvitationResource + StaffInvitationForm + MarketLocationResource + MarketSpaceGroupEpisodeResource + CreateMarketLocation + EditMarketLocation + EditMarketSpace + MarketSpaceResource + CreateMarketSpace + TenantContractResource + ListTenantContracts + TenantAccrualResource + TenantAccrualsTable + ListTenantAccruals + MarketDocumentResource + ListMarketDocuments + MarketDocumentActivityEventResource + 1C reconciliation report переведены', 'status' => 'in_progress'],
                ['title' => 'Dashboard/widgets/Livewire используют единый context: 17 widget + Dashboard page read/write sync + MarketSwitcherWidget sync + StaffLiveFeed + OnlineStaffRail + QuickChatDrawer переведены', 'status' => 'in_progress'],
                ['title' => 'Карта рынка использует тот же market_id: MapReviewResults + основной экран карты + review Blade partials + AppServiceProvider map-review routes переведены', 'status' => 'done'],
                ['title' => '1C API выставляет context из integration token: payments + settlements + contract debts + contracts + accruals endpoints подготовлены', 'status' => 'done'],
                ['title' => 'Jobs/commands получают market_id явно: 1C finance commands, scheduled calendar/snapshot commands, read-only audit/report commands, preview/apply contract maintenance commands, notification health-check, market-admin notification limiter, occupancy reconcile, maintenance reconcile, space-review reconcile, positive space-review conflict audit, stale tenant contract archive, stale market-space group expire, market-space group backfill, market-space group episode backfill, tenant cabinet user ensure, tenant debt status reset, marketplace duplicate cleanup, marketplace announcements dedupe, marketplace slides seed defaults, marketplace demo image assignment, marketplace images localize, market holiday image generation, marketplace demo asset localization, marketplace demo asset sync, marketplace demo asset warm, marketplace demo asset permissions repair, marketplace preview backfill, market holidays seasonal promotions, sanitary calendar generation, market document trash purge, calendar task generation и operation snapshot rebuild подготовлены', 'status' => 'in_progress'],
                ['title' => 'Smoke matrix для UI/API/jobs: regression guards для API, 1C commands, scheduled commands, audit commands, preview/apply commands, notification health command, market-admin notification limiter command, occupancy reconcile command, maintenance reconcile command, space-review reconcile command, positive space-review conflict audit command, stale tenant contract archive command, stale market-space group expire command, market-space group backfill command, market-space group episode backfill command, tenant cabinet user ensure command, tenant debt status reset command, marketplace duplicate cleanup command, marketplace announcements dedupe command, marketplace slides seed defaults command, marketplace demo image assignment command, marketplace images localize command, market holiday image generation command, marketplace demo asset localization command, marketplace demo asset sync command, marketplace demo asset warm command, marketplace demo asset permissions repair command, marketplace preview backfill command, market holidays seasonal promotions command, sanitary calendar generation command, market document trash purge command, calendar task generation command, operation snapshot rebuild command и 1C reconcile cutover diagnostics добавлены', 'status' => 'in_progress'],
            ],
        ],
        [
            'key' => 'write_guards',
            'title' => '4. Write guards',
            'weight' => 14,
            'status' => 'in_progress',
            'summary' => 'Защита от cross-market связей при создании и обновлении данных.',
            'items' => [
                ['title' => 'Same-market validator/service', 'status' => 'done'],
                ['title' => 'Guards для договоров и мест', 'status' => 'done'],
                ['title' => 'Guards для начислений и платежей: offline-команды и live 1C accruals/payments', 'status' => 'done'],
                ['title' => 'Guards для документов и шаринга', 'status' => 'done'],
                ['title' => 'Guards для marketplace', 'status' => 'done'],
                ['title' => 'Cross-market tests create/update', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'demo_pilot',
            'title' => '5. Demo market и пилот',
            'weight' => 12,
            'status' => 'in_progress',
            'summary' => 'Безопасное демо с синтетическими данными и пилотный контур для первых клиентов.',
            'items' => [
                ['title' => 'Safety flags и prod write barrier для demo/pilot контура', 'status' => 'done'],
                ['title' => 'demo:provision dry-run план без записи данных', 'status' => 'done'],
                ['title' => 'demo:provision preflight adapter проверяет payload, таблицы и колонки без записи данных', 'status' => 'done'],
                ['title' => 'demo:provision idempotent write adapter для local/staging: demo market, users, market_locations, tenants, market_spaces, map_shapes, tenant_contracts, tenant_accruals и tenant_payments', 'status' => 'done'],
                ['title' => 'demo:reset dry-run/execute с удалением только synthetic demo-записей, включая map_shapes, без удаления market shell', 'status' => 'done'],
                ['title' => 'Состав синтетических пользователей, арендаторов, мест, карты, договоров, финансов и marketplace описан в data builder', 'status' => 'done'],
                ['title' => 'Синтетические арендаторы, места, договоры и финансы', 'status' => 'done'],
                ['title' => 'Демо-пользователи директор/админ/оператор/арендатор', 'status' => 'done'],
                ['title' => 'Механизм демо-доступов: пароль только через env, владелец показа 321_123@bk.ru, без перезаписи реального аккаунта', 'status' => 'done'],
                ['title' => 'Простая карта рынка с 5 фигурами мест', 'status' => 'done'],
                ['title' => 'Внешние интеграции в демо выключены', 'status' => 'done'],
                ['title' => 'Demo script на 15 минут', 'status' => 'done'],
            ],
        ],
        [
            'key' => 'landing_sales',
            'title' => '6. Сайт и воронка продаж',
            'weight' => 8,
            'status' => 'in_progress',
            'summary' => 'Сайт-визитка, заявка на демо, пилот и коммерческая воронка.',
            'items' => [
                ['title' => 'Landing page', 'status' => 'done'],
                ['title' => 'Форма заявки', 'status' => 'in_progress'],
                ['title' => 'Сохранение и уведомления по заявкам', 'status' => 'in_progress'],
                ['title' => 'Презентация и КП', 'status' => 'pending'],
                ['title' => 'Таблица первых лидов', 'status' => 'pending'],
            ],
        ],
        [
            'key' => 'rollout',
            'title' => '7. Staging и prod rollout',
            'weight' => 10,
            'status' => 'in_progress',
            'summary' => 'Контролируемый выпуск: staging, flags off, smoke, потом prod только с подтверждением для рискованных действий.',
            'items' => [
                ['title' => 'Staging deploy с flags off', 'status' => 'done'],
                ['title' => 'Staging smoke с flags off', 'status' => 'done'],
                ['title' => 'Staging demo:provision one-shot с временными flags и без постоянного включения demo flags', 'status' => 'done'],
                ['title' => 'Prod deploy с flags off', 'status' => 'done'],
                ['title' => 'Prod flags on отдельным решением', 'status' => 'pending'],
                ['title' => 'Rollback drill через flags', 'status' => 'pending'],
            ],
        ],
    ],
    'risks' => [
        [
            'title' => 'Главный риск',
            'description' => 'Случайно повредить prod или скрыть данные из-за слишком раннего scope.',
            'mitigation' => 'Все scope/strict-write изменения только через flags, сначала local/staging, prod с flags off.',
        ],
        [
            'title' => '1C и фоновые процессы',
            'description' => 'API/jobs могут выполняться без session context.',
            'mitigation' => 'Перед включением scope все API/jobs должны явно выставлять MarketContext.',
        ],
        [
            'title' => 'Cross-market связи',
            'description' => 'FK проверяют существование записей, но не совпадение market_id.',
            'mitigation' => 'Write guards и тесты create/update для критичных сущностей.',
        ],
    ],
];
